window.BDL_PRODUCTS = [
  {brand:"COCOÀGE COSMETICS",product:"Delight Caffeine 24K Eye Cream",size:"30 mL / 1 fl oz",retail:"$795",price:"",categoryLabel:"Skincare / Eye Care",categories:["new","skincare"],status:"Available",image:"https://cocoagecosmetics.com/cdn/shop/products/Cocoage_Delight-Caffeine-24K-Gold-Eye-Cream_1600x_0186fe5c-40bd-4abd-a154-75bb167d1fa2_1600x.jpg?v=1529084800"},
  {brand:"COCOÀGE COSMETICS",product:"HOT TEMP Intense 24K Anti-Wrinkle Cream",size:"30 mL / 1 fl oz",retail:"$1,200",price:"",categoryLabel:"Skincare / Moisturizer",categories:["new","skincare"],status:"Available",image:"https://cocoagecosmetics.com/cdn/shop/products/Cocoage_HOT-TEMP-Intense-24K-Gold-Anti-Wrinkle-Cream_1600x_449c6d67-a0c9-4dfe-b32d-585bd16a8782_1600x.jpg?v=1529084963"},
  {brand:"COCOÀGE COSMETICS",product:"24K Cocoa Facial Peeling Gel",size:"50 mL / 1.7 fl oz",retail:"$289",price:"",categoryLabel:"Skincare / Exfoliator",categories:["new","skincare"],status:"Available",image:"https://cocoagecosmetics.com/cdn/shop/products/Cocoage_24K-Gold-Cocoa-Facial-Peeling-Gel_1600x_45d65107-52a5-499b-8d63-c20a39af73bb_1600x.jpg?v=1529083909"},
  {brand:"LÁTOÜA MILLE",product:"Eye Concentrate Gel for Dark Circles Hyaluronic Acid + Multi-Peptide",size:"50 mL / 1.7 fl oz",retail:"$1,250",price:"",categoryLabel:"Skincare / Eye Care",categories:["new","skincare"],status:"Available",image:"https://latouamille.com/cdn/shop/files/LMEE001-Product_Box.jpg?v=1746631640&width=1946"},
  {brand:"PRÉDIRÉ PARIS",product:"Dead Sea Mud Purifying Ritual Set",size:"3-Piece Skincare Set + Applicator",retail:"$399.99",price:"",categoryLabel:"Skincare / Gift Set",categories:["new","skincare","gifts"],status:"Available",image:"https://predireparis.com/cdn/shop/files/PP-MUDMASKSETwbox_6dbd9163-a96e-45a6-8a93-5650120e2579.jpg?v=1775833065&width=1946"},
  {brand:"ELIYA SKIN",product:"Volcanic Instant Detox Mask - Purification Formula for Deep Pore Cleansing",size:"100 g / 3.53 oz",retail:"$299.99",price:"",categoryLabel:"Skincare / Face Mask",categories:["new","skincare"],status:"Available",image:"https://eliyaskin.com/cdn/shop/files/EA-DETOXMASKwbox_4799677e-ef66-4754-8d8f-ca0937bac41b.jpg?v=1787234764&width=914"},
  {brand:"PRÉDIRÉ PARIS",product:"Double-Acting Facial Moisturizer Vitamin C Based Hydrating & Whitening",size:"30 mL / 1 fl oz",retail:"$400",price:"",categoryLabel:"Skincare / Moisturizer",categories:["new","skincare"],status:"Available",image:"https://predireparis.com/cdn/shop/files/PP2-MOIS-VC-Product_Box.jpg?v=1717691382&width=416"},
  {brand:"PRÉDIRÉ PARIS",product:"50X Premium Vitamin C Whitening Serum",size:"30 mL / 1 fl oz",retail:"$400",price:"",categoryLabel:"Skincare / Serum",categories:["new","skincare"],status:"2 Available",image:"https://predireparis.com/cdn/shop/products/PAD006-ORANGE-ProductImages-03_1024x1024%402x.jpg?v=1682016726"},
  {brand:"PRÉDIRÉ PARIS",product:"Daily Defence Multi-Peptide Renewal Dropper",size:"30 mL / 1 fl oz",retail:"$299.99",price:"",categoryLabel:"Skincare / Serum",categories:["new","skincare"],status:"Available",image:"https://predireparis.com/cdn/shop/files/PG-DROP03wbox.jpg?v=1770842903&width=1946"},
  {brand:"ROYALE",product:"24K Gold Silk Radiance Keratin Hair Serum",size:"50 mL / 1.69 fl oz",retail:"$250",price:"",categoryLabel:"Hair / Serum",categories:["new","hair"],status:"Available",image:"https://royaleusa.com/cdn/shop/files/RGLOW-SERUMwbox_19bb99f7-c513-4c08-8bc3-016ff6dd5663_2400x.jpg?v=1775659913"},
  {brand:"ROYALE",product:"24K Gold Silk Radiance Keratin Hair Mask",size:"200 g / 7.05 oz",retail:"$99.99",price:"",categoryLabel:"Hair / Mask",categories:["new","hair"],status:"Available",image:"https://royaleusa.com/cdn/shop/files/RGLOW-MASK_2400x.jpg?v=1776369079"},
  {brand:"ROYALE",product:"Rescue Softening Shampoo - Vanilla",size:"150 mL / 5.07 fl oz",retail:"$75",price:"",categoryLabel:"Hair / Shampoo",categories:["new","hair"],status:"Available",image:"https://royaleusa.com/cdn/shop/files/RHS04_500x.jpg?v=1776365607"},
  {brand:"ROYALE",product:"Rescue Softening Conditioner - Vanilla",size:"150 mL / 5.07 fl oz",retail:"$75",price:"",categoryLabel:"Hair / Conditioner",categories:["new","hair"],status:"Available",image:"https://royaleusa.com/cdn/shop/files/RHC04_2400x.jpg?v=1776364579"},
  {brand:"PRÉDIRÉ PARIS",product:"Multi-Purpose Anti-Aging Skin Care Device",size:"7-Color LED Skin Care Device",retail:"$24,000",price:"",categoryLabel:"Skincare / Device",categories:["new","skincare"],status:"Available",image:"https://predireparis.com/cdn/shop/files/PP-MULTIDEVICE-Product_Box1.jpg?v=1716928099&width=416"},
  {brand:"PRÉDIRÉ PARIS",product:"Prestige Element Multi-Purpose Face Mask",size:"Cordless Multi-Spectrum LED Face Mask",retail:"$4,999.99",price:"",categoryLabel:"Skincare / LED Device",categories:["new","skincare"],status:"Available",image:"https://predireparis.com/cdn/shop/files/PP-PRESTIGE-MASKwbox.jpg?v=1770415039&width=416"},
  {brand:"PRÉDIRÉ PARIS",product:"V-Sculpt EMS & Light Therapy Device",size:"Rechargeable EMS & LED Device",retail:"$4,800",price:"",categoryLabel:"Skincare / Device",categories:["new","skincare"],status:"2 Available",image:"https://predireparis.com/cdn/shop/files/PP-EMSPROwbox.jpg?v=1770415070&width=416"}
];